name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Python syntax check
        run: |
          set -e
          pyfiles="$(git ls-files '*.py' || true)"
          if [ -n "$pyfiles" ]; then
            python -m py_compile $pyfiles
          else
            echo "No Python files to check."
          fi

      - name: Shell script syntax check
        run: |
          set -e
          if [ -d tools ]; then
            find tools -type f -name "*.sh" -print0 | xargs -0 -I{} bash -n "{}"
          else
            echo "No tools/ directory."
          fi
